package com.heavens.stream.enums;

public enum CodeType {
    NUMBERS_ONLY,
    NUMBERS_CHARACTER_LOWER_CASE,
    NUMBERS_CHARACTER_UPPER_CASE,
    CHARACTERS_UPPER_CASE_ONLY,
    CHARACTERS_LOWER_CASE_ONLY,
    CHARACTERS_ONLY,
    CHARACTERS
}
